image: node:12.16.1-alpine3.11

before_script:
    - apk add g++ make python
    - npm ci

stages:
    - check-formatting
    - deploy

prettifier-check:
    stage: check-formatting
    only:
        - master
    script:
        - npm run prettier:check

deploy-qa:
    stage: deploy
    only:
        - master
    script:
        - export AWS_ACCESS_KEY_ID=${QA_AWS_ACCESS_KEY_ID}
        - export AWS_SECRET_ACCESS_KEY=${QA_AWS_SECRET_ACCESS_KEY}
        - npm run deploy

deploy-live-envs:
    stage: deploy
    only:
        - master
    when: manual
    script:
        - export AWS_ACCESS_KEY_ID=${FLOOR28_AWS_ACCESS_KEY_ID}
        - export AWS_SECRET_ACCESS_KEY=${FLOOR28_AWS_SECRET_ACCESS_KEY}
        - npm run deploy
        - export AWS_ACCESS_KEY_ID=${PARIS_STARTUP_HUB_AWS_ACCESS_KEY_ID}
        - export AWS_SECRET_ACCESS_KEY=${PARIS_STARTUP_HUB_AWS_SECRET_ACCESS_KEY}
        - npm run deploy
