service:
    name: ws-lambda-workshop

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    memorySize: 128
    websocketsApiName: ws-lambda-workshop-api

functions:
    onConnect:
        handler: src/connection.onConnect
        events:
            -   websocket: $connect
