service: ws-lambda-workshop

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    memorySize: 128
    websocketsApiName: ws-lambda-workshop-api

functions:
    onConnect:
        handler: src/connection.onConnect
        events:
            -   websocket: $connect
    onMessage:
        handler: src/connection.onMessage
        events:
            -   websocket: $default
